// Inline SVG logo — kept as a string so the HTML report is fully self-contained
// (no external asset references).
const LOGO_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="48" height="48" aria-hidden="true"><rect width="256" height="256" rx="40" fill="#0B1220"/><g transform="translate(128 128)" fill="none" stroke="#22D3EE" stroke-width="3" opacity="0.35"><ellipse rx="84" ry="32"/><ellipse rx="84" ry="32" transform="rotate(60)"/><ellipse rx="84" ry="32" transform="rotate(120)"/></g><rect x="20" y="120" width="216" height="16" fill="#22D3EE" opacity="0.08"/><g stroke="#22D3EE" stroke-width="14" stroke-linecap="round" fill="none"><line x1="72" y1="72" x2="184" y2="184"/><line x1="184" y1="72" x2="72" y2="184"/></g><circle cx="128" cy="128" r="10" fill="#0B1220"/><circle cx="128" cy="128" r="6" fill="#22D3EE"/></svg>`;

export function htmlShell(opts: {
  title: string;
  dataInline?: string;          // when embedded
  dataExternalPath?: string;    // when split
}): string {
  const data = opts.dataInline
    ? `<script type="application/json" id="data">${opts.dataInline}</script>`
    : `<script>
        fetch("${opts.dataExternalPath}").then(r => r.json()).then(data => {
          window.__RX_DATA__ = data;
          document.dispatchEvent(new Event("rx:data-loaded"));
        });
      </script>`;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>${opts.title}</title>
  <link rel="icon" href='data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" rx="40" fill="%230B1220"/><g stroke="%2322D3EE" stroke-width="14" stroke-linecap="round" fill="none"><line x1="72" y1="72" x2="184" y2="184"/><line x1="184" y1="72" x2="72" y2="184"/></g><circle cx="128" cy="128" r="6" fill="%2322D3EE"/></svg>'/>
  <style>
    body{font-family:ui-sans-serif,system-ui,sans-serif;margin:0;padding:0;color:#0f172a;background:#f8fafc}
    header{display:flex;align-items:center;gap:16px;padding:20px 32px;background:#0B1220;color:#e2e8f0}
    header .brand{display:flex;align-items:center;gap:14px}
    header h1{margin:0;font-size:20px;font-weight:700;letter-spacing:-0.01em}
    header h1 .accent{color:#22D3EE}
    header .meta{margin-left:auto;font-size:13px;color:#94a3b8;text-align:right;font-family:ui-monospace,Menlo,monospace}
    main{max-width:1200px;margin:0 auto;padding:24px 32px 64px}
    h2{margin:32px 0 8px;font-size:16px;color:#0f172a}
    table{border-collapse:collapse;width:100%;margin:8px 0 24px;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 2px rgba(15,23,42,0.04),0 1px 1px rgba(15,23,42,0.06)}
    th,td{border-bottom:1px solid #e2e8f0;padding:8px 12px;text-align:left;font-size:13px}
    th{background:#f1f5f9;cursor:pointer;font-weight:600;color:#334155}
    tr:last-child td{border-bottom:none}
    tr:hover td{background:#f8fafc}
    details{margin:4px 0}
    summary{cursor:pointer}
    code{font-family:ui-monospace,Menlo,monospace;font-size:12px;color:#0f172a;background:#f1f5f9;padding:1px 5px;border-radius:4px}
    .dim{color:#64748b}
    .pill{display:inline-block;padding:1px 6px;border-radius:8px;background:#f1f5f9;font-size:11px;color:#334155}
    .pill.cyan{background:rgba(34,211,238,0.12);color:#0e7490}
    footer{max-width:1200px;margin:0 auto;padding:16px 32px;color:#94a3b8;font-size:12px;border-top:1px solid #e2e8f0;text-align:center}
    footer a{color:#22D3EE;text-decoration:none}
  </style>
</head>
<body>
  <header>
    <div class="brand">
      ${LOGO_SVG}
      <h1>react-<span class="accent">xray</span></h1>
    </div>
    <div class="meta" id="header-meta"></div>
  </header>
  ${data}
  <main><div id="app">Loading…</div></main>
  <footer>generated by <a href="https://github.com/chintan-diwakar/react-xray">react-xray</a></footer>
  <script>
    (function(){
      function read(){
        var el=document.getElementById("data");
        if(el) return JSON.parse(el.textContent||"{}");
        return window.__RX_DATA__||null;
      }
      function esc(s){return String(s).replace(/[&<>"']/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]);});}
      function render(d){
        if(!d){document.getElementById("app").textContent="No data.";return;}
        var meta=document.getElementById("header-meta");
        meta.innerHTML='<span class="pill cyan">'+esc(d.meta.framework)+'</span> &nbsp;'+esc(String(d.meta.fileCount))+' files &middot; '+(d.meta.durationMs/1000).toFixed(2)+'s';
        var html="";
        html+="<p class=dim>"+esc(d.meta.rootDir)+"</p>";

        html+="<h2>Summary</h2>";
        html+="<table><tbody>";
        var used=(d.components||[]).length-((d.unused||{}).strictlyUnused||[]).length;
        html+="<tr><td>Components</td><td>"+(d.components||[]).length+" (<span class=dim>used</span> "+used+" &middot; <span class=dim>unused</span> "+((d.unused||{}).strictlyUnused||[]).length+")</td></tr>";
        html+="<tr><td>Pages</td><td>"+(d.pages||[]).length+"</td></tr>";
        var instances=0;(d.externals||[]).forEach(function(e){instances+=e.instances||0;});
        html+="<tr><td>External usage</td><td>"+(d.externals||[]).length+" packages &middot; "+instances+" instances</td></tr>";
        html+="<tr><td>Total LOC</td><td>"+(((d.stats||{}).totalLOC)||0).toLocaleString()+"</td></tr>";
        html+="</tbody></table>";

        html+="<h2>Per-page reachability</h2>";
        html+="<table><thead><tr><th>Route</th><th>Direct</th><th>Transitive</th><th>External pkgs</th><th>LOC reached</th></tr></thead><tbody>";
        (d.matrix||[]).forEach(function(row){
          html+="<tr><td><code>"+esc(row.pageRoute)+"</code></td><td>"+row.directComponents.length+"</td><td>"+row.transitiveComponents.length+"</td><td><span class=dim>"+esc((row.externalPackages||[]).join(", "))+"</span></td><td>"+row.locReached+"</td></tr>";
        });
        html+="</tbody></table>";

        html+="<h2>Unused (strictly)</h2>";
        html+="<table><thead><tr><th>Component</th><th>File</th><th>LOC</th><th>Reasons</th></tr></thead><tbody>";
        (((d.unused)||{}).strictlyUnused||[]).forEach(function(u){
          html+="<tr><td><strong>"+esc(u.name)+"</strong></td><td><code>"+esc(u.file)+"</code></td><td>"+u.loc+"</td><td><span class=dim>"+esc((u.reasons||[]).join("; "))+"</span></td></tr>";
        });
        html+="</tbody></table>";

        html+="<h2>Library adoption</h2>";
        html+="<table><thead><tr><th>Package</th><th>Component</th><th>Instances</th></tr></thead><tbody>";
        (d.externals||[]).forEach(function(e){
          html+="<tr><td><code>"+esc(e.package)+"</code></td><td>"+esc(e.name)+"</td><td>"+e.instances+"</td></tr>";
        });
        html+="</tbody></table>";

        document.getElementById("app").innerHTML=html;
      }
      var d=read();
      if(d){render(d);}
      else{document.addEventListener("rx:data-loaded",function(){render(window.__RX_DATA__);});}
    })();
  </script>
</body>
</html>`;
}
